/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package net.flexmojos.oss.generator {

    [Bindable]
    [RemoteClass(alias="net.flexmojos.oss.generator.SimpleChild")]
    public class SimpleChild extends SimpleChildBase {
    }
}