/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Tue Jul 22 10:09:36 BRT 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package info.flexmojos.generator {

    [Bindable]
    [RemoteClass(alias="info.flexmojos.generator.SimplePojo")]
    public class SimplePojo extends SimplePojoBase {
    }
}