/**
 * Generated by Gas3 v2.3.2 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.apache.flex.swc {

    [Bindable]
    [RemoteClass(alias="org.apache.flex.swc.SWCDigest")]
    public class SWCDigest extends SWCDigestBase {
    }

}