/**
 * Flexmojos is a set of maven goals to allow maven users to compile, optimize and test Flex SWF, Flex SWC, Air SWF and Air SWC.
 * Copyright (C) 2008-2012  Marvin Froeder <marvin@flexmojos.net>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.sonatype.flexmojos.test.report
{

    [RemoteClass( alias="org.sonatype.flexmojos.test.report.TestCoverageReport" )]
    public class TestCoverageReport extends TestCoverageReportBase
    {

        public function TestCoverageReport( classname:String )
        {
            super.classname = classname;
            super.touchs = new Array();
        }

        public function touch( lineNumber:int ):void
        {
            touchs.splice( touchs.length, 0, lineNumber );
        }

        public function toXml():String
        {
            var genxml:String = "<coverage classname=\""+ classname + "\">";

            for each ( var line:int in touchs )
            {
                  genxml = genxml.concat("<touch>",line,"</touch>");
            }
            
            genxml += "</coverage>";

            return genxml;
        }

    }
}