/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.sonatype.flexmojos.test.report
{

    [Bindable]
    [RemoteClass( alias="org.sonatype.flexmojos.test.report.TestCoverageReport" )]
    public class TestCoverageReport extends TestCoverageReportBase
    {



        public function TestCoverageReport( classname:String )
        {
            super.classname = classname;
            super.touchs = new Array();
        }

        public function touch( lineNumber:int ):void
        {
            touchs.splice( touchs.length, 0, lineNumber );
        }

        public function toXml():XML
        {
            var genxml:String = "<coverage classname =\""+ classname + "\">";

            for each ( var line:int in touchs )
            {
//                var touchXml:XML = <touch>{ line} 
//                    </touch>;
//                genxml = genxml.appendChild( touchXml );
genxml += "<touch>" + line + "</touch>";
            }
            
            genxml += "</coverage>";
            
            return XML(genxml);
        }

    }
}