/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package info.flexmojos.compile.test.report {

    [Bindable]
    [RemoteClass(alias="info.flexmojos.compile.test.report.TestMethodReport")]
    public class TestMethodReport extends TestMethodReportBase {
    	
    	/*
		    <testMethodReport>
		      <error>
		        <message>message</message>
		        <stackTrace>test</stackTrace>
		        <type>my.error.1</type>
		      </error>
		      <failure>
		        <message>message</message>
		        <stackTrace>test</stackTrace>
		        <type>my.error.1</type>
		      </failure>
		      <name>testMethod</name>
		      <time>25.3</time>
		    </testMethodReport>
    	 */
    	public function toXml():XML
    	{
    		var xml:XML =
		    <testMethodReport>
		      <name> { name } </name>
		      <time> { time } </time>
		    </testMethodReport>;
    			
    		if(error != null) {
				var errorXml:XML =
			      <error>
			        <message> {error.message} </message>
			        <stackTrace> { error.stackTrace } </stackTrace>
			        <type> { error.type } </type>
			      </error>;
 
    			xml = xml.appendChild(errorXml);
    		}

    		if(failure != null) {
				var failureXml:XML =
			      <failure>
			        <message> { failure.message } </message>
			        <stackTrace> { failure.stackTrace } </stackTrace>
			        <type> { failure.type } </type>
			      </failure>;
 
    			xml = xml.appendChild(failureXml);
    		}

    		return xml;
    	}
    }
}