/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package info.flexmojos.compile.test.report {

    [Bindable]
    [RemoteClass(alias="info.flexmojos.compile.test.report.TestCaseReport")]
    public class TestCaseReport extends TestCaseReportBase {

		public function TestCaseReport()
		{
			methods = new Array();
		}

		/*
		 * Return the method Object from the internal TestSuite model for the
		 * currently executing method on a Test.
		 * @param test the Test.
		 * @return the method Object.
		 */
		public function getMethod( methodName:String ):TestMethodReport
		{
			var method:TestMethodReport;
			for each (method in methods) 
			{
				if(method.name == methodName)
				{
					return method;
				}
			}
			
			method = new TestMethodReport(); 
			method.name = methodName;
			
			methods.push(method);
			
			return method;
		}

		/*
			<testCaseReport>
			  <errors>2</errors>
			  <failures>2</failures>
			  <methods>
			    <testMethodReport>
			      <error>
			        <message>message</message>
			        <stackTrace>test</stackTrace>
			        <type>my.error.1</type>
			      </error>
			      <failure>
			        <message>message</message>
			        <stackTrace>test</stackTrace>
			        <type>my.error.1</type>
			      </failure>
			      <name>testMethod</name>
			      <time>25.3</time>
			    </testMethodReport>
			  </methods>
			  <name>info.flexmojos.Test1</name>
			  <tests>10</tests>
			  <time>323.5</time>
			</testCaseReport>
		 */
		public function toXml():XML {
			
			var methodsXml:XML = <methods></methods>;
			for each (var methodReport:TestMethodReport in methods)
			{
				methodsXml = methodsXml.appendChild(methodReport.toXml());
			}
			
			var xml:XML =
				<testCaseReport>
					<errors> { errors } </errors>
					<failures> { failures } </failures>
					{ methodsXml }
					<name> { name } </name>
					<tests> { tests } </tests>
					<time> { time } </time>
				</testCaseReport>;
				
			return xml;
		}

    }
}