/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.sonatype.flexmojos.todolist.domain {

    [Bindable]
    [RemoteClass(alias="org.sonatype.flexmojos.todolist.domain.TodoItem")]
    public class TodoItem extends TodoItemBase {
    }
}