/**
 * Generated by Gas3 v1.1.0 (Granite Data Services) on Sat Jul 05 11:33:34 BRT 2008.
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package tests {

import info.flexmojos.generator.*;
import flexunit.framework.TestCase;

	public class InheritTest extends TestCase {

		public function testGeneratedInherit() : void
		{
			var sc:SimpleChild = new SimpleChild();

			assertTrue( sc is SimplePojo );
		}

	}
}
