/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * WARNING: DO NOT CHANGE THIS FILE. IT MAY BE OVERRIDDEN EACH TIME YOU USE
 * THE GENERATOR. CHANGE INSTEAD THE INHERITED INTERFACE (TodoService.as).
 */

package org.sonatype.flexmojos.todolist.business {

    import flash.events.IEventDispatcher;
    
    import mx.rpc.AsyncToken;
    
    import org.sonatype.flexmojos.todolist.domain.TodoItem;

    public interface ITodoService extends IEventDispatcher {

	    function remove( todoItem:TodoItem ):AsyncToken;
	
	    function save( todoItem:TodoItem ):AsyncToken;
	
	    function findById( todoItem:TodoItem ):AsyncToken;
	
	    function getList():AsyncToken;

    }
}