/**
 * Generated by Gas3 v1.1.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.sonatype.flexmojos.todolist.business {
	import flash.events.Event;
	import flash.events.IEventDispatcher;
	
	import mx.rpc.AsyncToken;
	import mx.rpc.remoting.RemoteObject;
	
	import org.sonatype.flexmojos.todolist.domain.TodoItem;
	

    public class TodoService implements ITodoService, IEventDispatcher {
    	
    	private var ro:RemoteObject;
    	
    	public function TodoService(destination:String) {
    		ro = new RemoteObject(destination);
    	}
    	
		public function addEventListener(type:String, listener:Function, useCapture:Boolean=false, priority:int=0, useWeakReference:Boolean=false):void
		{
			ro.addEventListener(type, listener, useCapture, priority, useWeakReference);
		}
		
		public function removeEventListener(type:String, listener:Function, useCapture:Boolean=false):void
		{
			ro.removeEventListener(type, listener, useCapture);
		}
		
		public function dispatchEvent(event:Event):Boolean
		{
			return ro.dispatchEvent(event);
		}
		
		public function hasEventListener(type:String):Boolean
		{
			return ro.hasEventListener(type);
		}
		
		public function willTrigger(type:String):Boolean
		{
			return ro.willTrigger(type);
		}
		
		public function remove(todoItem:TodoItem):AsyncToken
		{
			return ro.remove(todoItem);
		}
		
		public function save(todoItem:TodoItem):AsyncToken
		{
			return ro.save(todoItem);
		}
		
		public function findById(todoItem:TodoItem):AsyncToken
		{
			return ro.findById(todoItem);
		}
		
		public function getList():AsyncToken
		{
			return ro.getList();
		}
    	
    }
}